/*
-- Query: SELECT * FROM NailNow.Manicurist
LIMIT 0, 1000

-- Date: 2025-07-28 19:42
*/
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (1,'Camila','Santos','321.654.987-00','camila@email.com','Rua Bela Vista, 99','Porto Alegre','senha789');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (2,'Mirella','Costela','980.653.417-48','mirella.costela@ig.com.br','Fazenda Camila Nascimento, 29','Cunha Paulista','7YbXF0h0');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (3,'Milena','da Rocha','569.013.274-80','milena.da rocha@bol.com.br','Ladeira de Novaes, 96','da Luz de Moura','F8Rhjrep');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (4,'Clara','Silva','650.137.489-84','clara.silva@bol.com.br','Campo Ferreira, 25','Nogueira','6ibTudRC');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (5,'Valentina','Silva','832.507.146-07','valentina.silva@hotmail.com','Passarela Thales Novaes','da Paz do Galho','45H0uLXw');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (6,'Maria Julia','Almeida','426.907.581-30','maria julia.almeida@yahoo.com.br','Jardim de Teixeira','Pires das Flores','FLm9tPyF');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (7,'Júlia','Moraes','890.521.674-94','júlia.moraes@ig.com.br','Campo Gabrielly da Luz, 65','Fogaça','v2XEFvEp');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (8,'Ana Vitória','Cardoso','708.632.415-90','ana vitória.cardoso@uol.com.br','Ladeira de Novaes, 39','Souza','6LrPS7rJ');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (9,'Maria Luiza','Castro','594.172.638-46','maria luiza.castro@bol.com.br','Estação Cecília Pereira, 66','Nunes Paulista','7ZF6GEQs');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (10,'Camila','Peixoto','725.638.490-47','camila.peixoto@uol.com.br','Esplanada de Caldeira','Fernandes','RK7UdF17');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (11,'Isabella','Martins','879.034.216-03','isabella.martins@hotmail.com','Pátio Lorena Nunes, 2','Mendes','ei3OtmKk');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (12,'Carolina','Aragão','234.560.178-71','carolina.aragão@gmail.com','Recanto Vieira','Araújo','66Q5vOEy');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (13,'Alícia','Moraes','578.642.309-38','alícia.moraes@bol.com.br','Vereda Rafaela Pinto, 684','Viana de Dias','1GI0OqLj');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (14,'Alana','Pinto','430.921.856-33','alana.pinto@uol.com.br','Via Nogueira, 53','Pereira','n3QGyWGB');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (15,'Ana Sophia','Ramos','974.583.160-39','ana sophia.ramos@hotmail.com','Alameda de da Mata','Gomes','4050DEmw');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (16,'Helena','Cardoso','204.638.579-92','helena.cardoso@yahoo.com.br','Aeroporto Felipe Farias, 47','da Paz','57COXw9y');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (17,'Maysa','Jesus','350.681.794-93','maysa.jesus@yahoo.com.br','Ladeira Costa','Farias do Sul','0gSlFzgK');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (18,'Pietra','Teixeira','127.984.560-02','pietra.teixeira@gmail.com','Morro Mirella Cunha, 80','Gonçalves de Viana','BL7HGuYs');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (19,'Emanuella','Viana','570.694.328-10','emanuella.viana@gmail.com','Vale Lucca Martins, 9','da Mota do Galho','7HYr5e2w');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (20,'Ana Lívia','Rodrigues','310.459.628-05','ana lívia.rodrigues@gmail.com','Trevo Cardoso, 4','Cardoso de Rezende','k0oLrcWj');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (21,'Manuela','Castro','136.974.520-61','manuela.castro@bol.com.br','Pátio de Cavalcanti, 757','da Cunha','VeX2vRmz');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (22,'Maria Fernanda','Viana','364.295.708-00','maria fernanda.viana@yahoo.com.br','Rua Cunha, 50','da Rosa','og5YAy92');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (23,'Isabelly','Farias','348.079.126-31','isabelly.farias@ig.com.br','Estação Carolina Castro, 740','Caldeira','5rrELbnm');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (24,'Marcela','Barbosa','582.741.903-60','marcela.barbosa@uol.com.br','Travessa de Santos, 4','Gonçalves das Flores','5Z2E5Vlk');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (25,'Luiza','Novaes','938.102.765-02','luiza.novaes@gmail.com','Praça Thomas Monteiro, 65','Lima','2LctvEg9');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (26,'Mariane','da Conceição','405.782.316-62','mariane.da conceição@yahoo.com.br','Setor de da Rosa, 98','Vieira do Amparo','9fNuXF3e');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (27,'Milena','Alves','164.582.039-42','milena.alves@ig.com.br','Parque Silva, 6','Teixeira de Carvalho','2Yi2GqUk');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (28,'Eduarda','Santos','409.387.256-29','eduarda.santos@yahoo.com.br','Conjunto de Carvalho, 48','Duarte Verde','uK2CNXjr');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (29,'Stella','da Conceição','925.047.631-07','stella.da conceição@hotmail.com','Largo Oliveira, 84','da Costa do Oeste','11EbbaEf');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (30,'Lívia','Ribeiro','526.371.408-44','lívia.ribeiro@gmail.com','Ladeira Oliveira, 43','da Luz','7TtQmbpi');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (31,'Lavínia','Ramos','036.594.827-65','lavínia.ramos@hotmail.com','Passarela Otávio Gomes, 72','Barros do Galho','2iOmwh8u');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (32,'Laís','da Paz','714.258.036-44','laís.da paz@ig.com.br','Núcleo de Cardoso, 368','Vieira das Flores','uZ09YBif');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (33,'Ana Vitória','Costela','304.895.726-00','ana vitória.costela@bol.com.br','Favela Ribeiro, 86','Almeida','c3p3Ri2q');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (34,'Ana Beatriz','Cavalcanti','628.574.139-55','ana beatriz.cavalcanti@gmail.com','Largo Vicente Nascimento','Pereira','T8rKCDCj');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (35,'Lara','Lopes','485.197.326-82','lara.lopes@uol.com.br','Vale Dias, 13','Araújo','7qnUzKYd');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (36,'Eloah','Campos','495.607.213-99','eloah.campos@ig.com.br','Alameda de da Luz, 65','Ribeiro de Azevedo','2tXKPekp');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (37,'Cecília','Melo','512.706.349-25','cecília.melo@bol.com.br','Estação Juliana Correia, 15','Oliveira de Minas','7wHI6mml');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (38,'Caroline','Mendes','784.621.053-07','caroline.mendes@hotmail.com','Quadra Nogueira, 510','Carvalho','6lk15ODb');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (39,'Natália','Costa','428.705.931-04','natália.costa@bol.com.br','Distrito Mariane Gomes, 232','Mendes da Prata','1u3N7Bhe');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (40,'Helena','da Paz','817.490.365-84','helena.da paz@yahoo.com.br','Quadra de Ribeiro, 33','Moreira das Flores','Kr2UWvTq');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (41,'Maitê','Cavalcanti','615.470.238-80','maitê.cavalcanti@uol.com.br','Feira Lavínia Farias, 727','Mendes','Q3ZLhWfs');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (42,'Maria Eduarda','Castro','724.309.581-04','maria eduarda.castro@yahoo.com.br','Viaduto de Caldeira, 4','Almeida','SIcR2Ven');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (43,'Ana Laura','Alves','986.712.053-12','ana laura.alves@gmail.com','Morro de Correia, 40','Novaes Alegre','6DM8mqMP');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (44,'Ana Julia','Aragão','276.108.349-04','ana julia.aragão@bol.com.br','Rodovia Ana Carolina Vieira, 66','da Mata','Z6EVPTMa');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (45,'Maria Luiza','Rocha','124.370.569-80','maria luiza.rocha@ig.com.br','Viaduto de Cardoso, 194','Teixeira do Sul','7ZKLOIAq');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (46,'Maria Luiza','da Cunha','904.657.812-76','maria luiza.da cunha@gmail.com','Campo de Freitas, 52','Fernandes do Sul','1TeMAfEB');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (47,'Bianca','da Costa','768.153.904-20','bianca.da costa@gmail.com','Condomínio Calebe da Cunha, 86','Ribeiro da Prata','3M8r0vRg');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (48,'Larissa','Fogaça','548.602.319-70','larissa.fogaça@ig.com.br','Estrada de Silveira, 62','Alves','61AnHB15');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (49,'Isis','da Mata','124.830.596-51','isis.da mata@ig.com.br','Jardim Igor Cardoso, 70','Melo do Norte','R4vIBU8f');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (50,'Raquel','Ferreira','109.842.367-40','raquel.ferreira@hotmail.com','Aeroporto de Azevedo, 34','Novaes Verde','w0RqmQXw');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (51,'Helena','Jesus','601.249.875-67','helena.jesus@ig.com.br','Sítio Barbosa, 53','Cavalcanti da Praia','7B21CEOu');
INSERT INTO `` (`IdManicurist`,`FirstName`,`LastName`,`CPF`,`Email`,`Address`,`City`,`Password`) VALUES (52,'Camila','Santos','321.654.987-00','camila@email.com','Rua Bela Vista, 99','São Paulo','senha789');
